body:
  - attributes:
      description: If any of these required steps are not taken, we may not be able to review your issue. Help us to help you!
      label: Example Request Checklist
      options:
        - label: I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha-examples/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
          required: true
        - label: I have searched for [related issues](https://github.com/mochajs/mocha-examples/issues?q=is%3Aissue), but none matched my issue.
          required: true
        - label: I want to provide a PR to resolve this
    type: checkboxes
  - attributes:
      description: What is the missing example or problem you'd like to address?
      label: Overview
    type: textarea
    validations:
      required: true
  - attributes:
      description: How would you like to solve this need?
      label: Suggested Solution
    type: textarea
    validations:
      required: true
  - attributes:
      description: Any additional info you'd like to provide.
      label: Additional Info
    type: textarea
description: Request that a new feature be added or an existing feature improved
labels:
  - 'status: in triage'
  - 'type: feature'
name: 🚀 Example
title: '🚀 Example: <short description of the example>'
